[package]
name = "dino-fight" # the name of the package
version = "0.1.0"    # the current version, obeying semver
authors = ["Curran McConnell <curran.mcconnell@protonmail.com>"]

[dependencies]
amethyst = "0.15.3"
